/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Uberui;
import uber.Cars;
import uber.Carshistory;

/**
 *
 * @author Sarvesh
 */
public class Carsframe extends javax.swing.JFrame {

    
    Carshistory hist;
    public Carsframe() {
        initComponents();
        hist = new Carshistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        Controlpanel = new javax.swing.JPanel();
        Create = new javax.swing.JButton();
        View = new javax.swing.JButton();
        Carcompany = new javax.swing.JButton();
        City = new javax.swing.JButton();
        Manufacturer = new javax.swing.JButton();
        Availability = new javax.swing.JButton();
        Maintainence = new javax.swing.JButton();
        Modelno = new javax.swing.JButton();
        Yearlist = new javax.swing.JButton();
        Serialno = new javax.swing.JButton();
        Seatoccupancy = new javax.swing.JButton();
        Workarea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Create.setText("Create");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });

        View.setText("View");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });

        Carcompany.setText("Carcompany");
        Carcompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarcompanyActionPerformed(evt);
            }
        });

        City.setText("City");
        City.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityActionPerformed(evt);
            }
        });

        Manufacturer.setText("Manufacturer");
        Manufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManufacturerActionPerformed(evt);
            }
        });

        Availability.setText("Availability");
        Availability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvailabilityActionPerformed(evt);
            }
        });

        Maintainence.setText("Maintainence");
        Maintainence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaintainenceActionPerformed(evt);
            }
        });

        Modelno.setText("Modelno");
        Modelno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModelnoActionPerformed(evt);
            }
        });

        Yearlist.setText("Yearlist");
        Yearlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearlistActionPerformed(evt);
            }
        });

        Serialno.setText("Serialno");
        Serialno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SerialnoActionPerformed(evt);
            }
        });

        Seatoccupancy.setText("Seatoccupancy");
        Seatoccupancy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeatoccupancyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlpanelLayout = new javax.swing.GroupLayout(Controlpanel);
        Controlpanel.setLayout(ControlpanelLayout);
        ControlpanelLayout.setHorizontalGroup(
            ControlpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlpanelLayout.createSequentialGroup()
                        .addComponent(Availability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlpanelLayout.createSequentialGroup()
                        .addComponent(Maintainence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(Modelno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlpanelLayout.createSequentialGroup()
                        .addGroup(ControlpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Serialno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Yearlist, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Create, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Carcompany, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(View, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(City, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Manufacturer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21))
                    .addComponent(Seatoccupancy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        ControlpanelLayout.setVerticalGroup(
            ControlpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlpanelLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(Create)
                .addGap(18, 18, 18)
                .addComponent(View)
                .addGap(23, 23, 23)
                .addComponent(Availability)
                .addGap(18, 18, 18)
                .addComponent(Maintainence)
                .addGap(18, 18, 18)
                .addComponent(Carcompany)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Modelno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(City)
                .addGap(18, 18, 18)
                .addComponent(Yearlist)
                .addGap(18, 18, 18)
                .addComponent(Serialno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Seatoccupancy)
                .addGap(23, 23, 23)
                .addComponent(Manufacturer)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        SplitPane.setLeftComponent(Controlpanel);

        javax.swing.GroupLayout WorkareaLayout = new javax.swing.GroupLayout(Workarea);
        Workarea.setLayout(WorkareaLayout);
        WorkareaLayout.setHorizontalGroup(
            WorkareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        WorkareaLayout.setVerticalGroup(
            WorkareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );

        SplitPane.setRightComponent(Workarea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        // TODO add your handling code here:
        Createcars createcars= new Createcars(hist);
        SplitPane.setRightComponent(createcars);
    }//GEN-LAST:event_CreateActionPerformed

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        // TODO add your handling code here:
        Viewcars viewcars= new Viewcars(hist);
        SplitPane.setRightComponent(viewcars);
    }//GEN-LAST:event_ViewActionPerformed

    private void AvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvailabilityActionPerformed
        // TODO add your handling code here:
        Availibility availibility = new Availibility(hist);
        SplitPane.setRightComponent(availibility);
    }//GEN-LAST:event_AvailabilityActionPerformed

    private void MaintainenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaintainenceActionPerformed
        // TODO add your handling code here:
        Maintainencecertificate maintainencecertificate = new Maintainencecertificate(hist);
        SplitPane.setRightComponent(maintainencecertificate);
    }//GEN-LAST:event_MaintainenceActionPerformed

    private void CarcompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarcompanyActionPerformed
        // TODO add your handling code here:
        Carcompany carcompany = new Carcompany(hist);
        SplitPane.setRightComponent(carcompany);
    }//GEN-LAST:event_CarcompanyActionPerformed

    private void ModelnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModelnoActionPerformed
        // TODO add your handling code here:
        Modelnumber modelnumber = new Modelnumber(hist);
        SplitPane.setRightComponent(modelnumber);
    }//GEN-LAST:event_ModelnoActionPerformed

    private void CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityActionPerformed
        // TODO add your handling code here:
        City city = new City(hist);
        SplitPane.setRightComponent(city);
    }//GEN-LAST:event_CityActionPerformed

    private void YearlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearlistActionPerformed
        // TODO add your handling code here:
        Yearmanufacture yearmanufacture = new Yearmanufacture(hist);
        SplitPane.setRightComponent(yearmanufacture);
    }//GEN-LAST:event_YearlistActionPerformed

    private void SerialnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SerialnoActionPerformed
        // TODO add your handling code here:
        Serialnumber serialnumber = new Serialnumber(hist);
        SplitPane.setRightComponent(serialnumber);
    }//GEN-LAST:event_SerialnoActionPerformed

    private void SeatoccupancyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeatoccupancyActionPerformed
        // TODO add your handling code here:
        Seats seats = new Seats(hist);
        SplitPane.setRightComponent(seats);
    }//GEN-LAST:event_SeatoccupancyActionPerformed

    private void ManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManufacturerActionPerformed
        // TODO add your handling code here:
        Carmanufacture carmanufacture = new Carmanufacture(hist);
        SplitPane.setRightComponent(carmanufacture);
    }//GEN-LAST:event_ManufacturerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carsframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carsframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carsframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carsframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carsframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Availability;
    private javax.swing.JButton Carcompany;
    private javax.swing.JButton City;
    private javax.swing.JPanel Controlpanel;
    private javax.swing.JButton Create;
    private javax.swing.JButton Maintainence;
    private javax.swing.JButton Manufacturer;
    private javax.swing.JButton Modelno;
    private javax.swing.JButton Seatoccupancy;
    private javax.swing.JButton Serialno;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton View;
    private javax.swing.JPanel Workarea;
    private javax.swing.JButton Yearlist;
    // End of variables declaration//GEN-END:variables
}
