/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Uberui;

import uber.Carshistory;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import uber.Cars;

/**
 *
 * @author Sarvesh
 */
public class Createcars extends javax.swing.JPanel {

    
    Carshistory hist;
    public Createcars(Carshistory hist) {
        initComponents();
        this.hist = hist;
        combo.removeAllItems();
        combo.addItem("5");
        combo.addItem("8");
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Carname = new javax.swing.JLabel();
        Company = new javax.swing.JLabel();
        Year = new javax.swing.JLabel();
        City = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        company = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        Serialno = new javax.swing.JLabel();
        serialno = new javax.swing.JTextField();
        Modelno = new javax.swing.JLabel();
        modelno = new javax.swing.JTextField();
        Manufacturer = new javax.swing.JLabel();
        manufacturer = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        combo = new javax.swing.JComboBox<>();
        Maintainencevalid = new javax.swing.JCheckBox();
        availability = new javax.swing.JCheckBox();
        seats = new javax.swing.JLabel();

        setForeground(new java.awt.Color(51, 255, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("               Create Details");

        Carname.setText("Carname");

        Company.setText("Company");

        Year.setText("Year");

        City.setText("City");

        Serialno.setText("Serialno");

        Modelno.setText("Modelno");

        Manufacturer.setText("Manufacturer");

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Maintainencevalid.setText("Maintainencevalid");

        availability.setText("Availability");

        seats.setText("Seats");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Company, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Carname)
                        .addComponent(Serialno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Modelno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Year, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Manufacturer)
                    .addComponent(seats))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Maintainencevalid)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(availability)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Submit))
                        .addComponent(manufacturer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                        .addComponent(modelno, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(company, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(year, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(city, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(serialno, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 264, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Carname)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Company)
                    .addComponent(company, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Year)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(City)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Serialno)
                    .addComponent(serialno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modelno)
                    .addComponent(modelno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Manufacturer)
                    .addComponent(manufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seats))
                .addGap(18, 18, 18)
                .addComponent(Maintainencevalid)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availability)
                    .addComponent(Submit))
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        int res = validateInput();
        if(res == 0){
        String name1 = name.getText();
        String company1 = company.getText();
        int year1 = Integer.parseInt(year.getText());
        String city1 = city.getText();
        String serial1 = serialno.getText();
        String model1 = modelno.getText();
        String manufacturer1 = manufacturer.getText();
        int seats = Integer.parseInt(combo.getSelectedItem().toString());
        boolean maintainence ;
        if(Maintainencevalid.isSelected()){
             maintainence = true;
        }
        else{
            maintainence = false;
        }
        boolean available ;
        if(availability.isSelected()){
             available = true;
        }
        else{
            available = false;
        }
        
        Cars cars = hist.addDetails();
        cars.setCarname(name1);
        cars.setCarcompany(company1);
        cars.setYear(year1);
        cars.setCity(city1);
        cars.setSerialno(serial1);
        cars.setModelno(model1);
        cars.setManufacturer(manufacturer1);
        cars.setSeatno(seats);
        cars.setMaintainencevalid(maintainence);
        cars.setAvailability(available);
        //cars.setDateTime("");
        
        JOptionPane.showMessageDialog(this,"New Car Record Added");
        
        name.setText("");
        company.setText("");
        year.setText("");
        city.setText("");
        serialno.setText("");
        modelno.setText("");
        manufacturer.setText("");
        Maintainencevalid.setSelected(false);
        availability.setSelected(false);
        combo.setSelectedItem("5");
        }
        
        
    }//GEN-LAST:event_SubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Carname;
    private javax.swing.JLabel City;
    private javax.swing.JLabel Company;
    private javax.swing.JCheckBox Maintainencevalid;
    private javax.swing.JLabel Manufacturer;
    private javax.swing.JLabel Modelno;
    private javax.swing.JLabel Serialno;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel Year;
    private javax.swing.JCheckBox availability;
    private javax.swing.JTextField city;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JTextField company;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField manufacturer;
    private javax.swing.JTextField modelno;
    private javax.swing.JTextField name;
    private javax.swing.JLabel seats;
    private javax.swing.JTextField serialno;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables

    private int validateInput() {
        int flag = 0;
         
         boolean isDuplicate = false;
         for(Cars cars: hist.getHist()){
            if(serialno.getText().equals(cars.getSerialno())){
                isDuplicate = true;
        }
        }
       
          if(serialno.getText().equals("")){
            flag = 1;
              JOptionPane.showMessageDialog(null,"Serial Number is required");
        } 
          if(isDuplicate == true){
            flag = 1;
              JOptionPane.showMessageDialog(null,"Please enter a unique serial number", "Error", JOptionPane.ERROR_MESSAGE);
        }
           
          if (manufacturer.getText().equals("")) {
              flag = 1;
              JOptionPane.showMessageDialog(null, "Manufacturer is required");
            }
           String yr = year.getText();
          
          if (yr.length() > 4) {
              flag = 1;
              JOptionPane.showMessageDialog(null, "Only 4 digits are allowed for year", "Error", JOptionPane.ERROR_MESSAGE);
            }
            if(company.getText().equals("")){
                flag =1;
            JOptionPane.showMessageDialog(null,"Company name is required");
        } 
            for(Cars cars: hist.getHist()){
            if(city.getText().equals(cars.getCity())){
                isDuplicate = true;
        }
        }
            if(city.getText().equals("")){
                flag =1;
            JOptionPane.showMessageDialog(null,"City is required");
        } 
            if(isDuplicate == true){
            flag = 1;
              JOptionPane.showMessageDialog(null,"Please enter unique city", "Error", JOptionPane.ERROR_MESSAGE);
        }
            String mno = modelno.getText();
            if(mno.length() > 10){
                flag =1;
            JOptionPane.showMessageDialog(null,"Model number should not exceed more than 10", "Error", JOptionPane.ERROR_MESSAGE);
        } 
  
            return flag;
    }
        
}
