/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Uberui;

import uber.Cars;
import uber.Carshistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat; 
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;


/**
 *
 * @author Sarvesh
 */
public class Viewcars extends javax.swing.JPanel {

    
    Carshistory hist;
    private Cars cars;
    public Viewcars(Carshistory hist) {
        initComponents();
        this.hist = hist;
        populateTable();
        refreshTable();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Carstbl = new javax.swing.JTable();
        View = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        updateStatus = new javax.swing.JLabel();
        updateRefresh = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        Carname = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        Company = new javax.swing.JLabel();
        company = new javax.swing.JTextField();
        Year = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        City = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        Serialno = new javax.swing.JLabel();
        serialno = new javax.swing.JTextField();
        Modelno = new javax.swing.JLabel();
        modelno = new javax.swing.JTextField();
        Manufacturer = new javax.swing.JLabel();
        manufacturer = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        seats2 = new javax.swing.JTextField();
        Maintainencevalid = new javax.swing.JCheckBox();
        availability = new javax.swing.JCheckBox();
        Catalog = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(701, 628));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("VIEW CAR RECORDS");

        Carstbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Car Name", "Manufacturer", "City", "Serial Number", "Available", "Updated Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Carstbl);

        View.setText("View");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Carname.setText("Carname");

        Company.setText("Company");

        Year.setText("Year");

        City.setText("City");

        Serialno.setText("Serialno");

        Modelno.setText("Modelno");

        Manufacturer.setText("Manufacturer");

        jLabel9.setText("Seats");

        Maintainencevalid.setText("Maintainencevalid");

        availability.setText("Availability");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(433, 433, 433)
                                .addComponent(updateRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addComponent(View)
                                .addGap(57, 57, 57)
                                .addComponent(Delete)
                                .addGap(17, 17, 17))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Company, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Carname)
                                        .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seats2, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(name)
                            .addComponent(company)
                            .addComponent(year)
                            .addComponent(city))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Serialno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Modelno))
                            .addComponent(Manufacturer)
                            .addComponent(Maintainencevalid)
                            .addComponent(availability))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 124, Short.MAX_VALUE)
                                .addComponent(updateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(manufacturer, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(modelno, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(serialno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(Update)
                .addGap(43, 43, 43)
                .addComponent(Save)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(View)
                    .addComponent(Delete)
                    .addComponent(updateRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Carname)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Company)
                            .addComponent(company, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Year)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(City)
                            .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(updateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(seats2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Serialno)
                            .addComponent(serialno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Modelno)
                            .addComponent(modelno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Manufacturer)
                            .addComponent(manufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Maintainencevalid)
                        .addGap(28, 28, 28)
                        .addComponent(availability)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Update)
                    .addComponent(Save))
                .addGap(170, 170, 170))
        );

        Catalog.setText("Catalog Last Updated on");
        Catalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatalogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(Catalog)
                .addContainerGap(588, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(Catalog)
                .addContainerGap(482, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        // TODO add your handling code here:
        int selected = Carstbl.getSelectedRow();
        if(selected < 0){
            JOptionPane.showMessageDialog(this,"Please selected the row to be viewed");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) Carstbl.getModel();
        Cars selectedCar = (Cars) model.getValueAt(selected,0);
        name.setText(selectedCar.getCarname());
        manufacturer.setText(selectedCar.getManufacturer());
        serialno.setText(selectedCar.getSerialno());
        city.setText(selectedCar.getCity());
        modelno.setText(selectedCar.getModelno());
        year.setText(String.valueOf(selectedCar.getYear()));
        Maintainencevalid.setSelected(selectedCar.isMaintainencevalid());
        company.setText(selectedCar.getCarcompany());
        seats2.setText(String.valueOf(selectedCar.getSeatno()));
        availability.setSelected(selectedCar.isAvailability());
    }//GEN-LAST:event_ViewActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        int selected = Carstbl.getSelectedRow();
        if(selected < 0){
            JOptionPane.showMessageDialog(this,"Please selected the row to be deleted");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) Carstbl.getModel();
        Cars selectedCar = (Cars) model.getValueAt(selected,0);
        hist.deleteDetails(selectedCar);
        JOptionPane.showMessageDialog(this,"Car Record Deleted");
        populateTable();

    }//GEN-LAST:event_DeleteActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:

        int selected = Carstbl.getSelectedRow();
        if(selected < 0){
            JOptionPane.showMessageDialog(this,"Please selected the row to be viewed");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) Carstbl.getModel();
        Cars selectedCar = (Cars) model.getValueAt(selected,0);
        selectedCar.setCity(city.getText());
        boolean mainvalid ;
        if(Maintainencevalid.isSelected()){
            mainvalid = true;
        }
        else{
            mainvalid = false;
        }
        selectedCar.setCarcompany(company.getText());
        boolean available ;
        if(availability.isSelected()){
            available = true;
        }
        else{
            available = false;
        }
        selectedCar.setAvailability(available);
        updateStatus.setText("");//date
        Date date = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("MM-dd-yyyy hh:mm:ss a");
        updateStatus.setText("Last Updated on : " + date);
        selectedCar.setDate(date);
        refreshTable();
    }//GEN-LAST:event_SaveActionPerformed
/**/
    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        name.setEditable(true);
        manufacturer.setEditable(true);
        serialno.setEditable(true);
        year.setEditable(true);
        seats2.setEditable(false);
        modelno.setEditable(true);
        city.setEditable(true);
        company.setEditable(true);
        //Maintainencevalid.setSelected(true);
    }//GEN-LAST:event_UpdateActionPerformed

    private void CatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatalogActionPerformed
        // TODO add your handling code here:
        ArrayList<Date> dateList = new ArrayList<Date>();
        SimpleDateFormat formatter = new SimpleDateFormat("MM-dd-yyyy hh:mm:ss a");
        for (Cars cars: hist.getHist()) {

            if(cars.getDate() != null){
                dateList.add(cars.getDate());
            }
        }
        if(dateList.size()>0){
            String maxDate = formatter.format(Collections.max(dateList));
            updateRefresh.setText(maxDate);
        }
        else{
            updateRefresh.setText("Never Updated");
        }

    }//GEN-LAST:event_CatalogActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Carname;
    private javax.swing.JTable Carstbl;
    private javax.swing.JButton Catalog;
    private javax.swing.JLabel City;
    private javax.swing.JLabel Company;
    private javax.swing.JButton Delete;
    private javax.swing.JCheckBox Maintainencevalid;
    private javax.swing.JLabel Manufacturer;
    private javax.swing.JLabel Modelno;
    private javax.swing.JButton Save;
    private javax.swing.JLabel Serialno;
    private javax.swing.JButton Update;
    private javax.swing.JButton View;
    private javax.swing.JLabel Year;
    private javax.swing.JCheckBox availability;
    private javax.swing.JTextField city;
    private javax.swing.JTextField company;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField manufacturer;
    private javax.swing.JTextField modelno;
    private javax.swing.JTextField name;
    private javax.swing.JTextField seats2;
    private javax.swing.JTextField serialno;
    private javax.swing.JLabel updateRefresh;
    private javax.swing.JLabel updateStatus;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables

    

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) Carstbl.getModel();
        model.setRowCount(0);
        
          for(Cars cars: hist.getHist()){
            Object[] row = new Object[6];
            row[0] = cars;
            row[1] = cars.getManufacturer();
            row[2] = cars.getCity();
            row[3] = cars.getSerialno();
            row[4] = cars.isAvailability();
            row[5] = cars.getDate();
    
            model.addRow(row);
            
        }
        }
    private void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) Carstbl.getModel();
        model.setRowCount(0);
        
        for(Cars cars: hist.getHist()){
            Object[] row = new Object[6];
            row[0] = cars;
            row[1] = cars.getManufacturer();
            row[2] = cars.getCity();
            row[3] = cars.getSerialno();
            row[4] = cars.isAvailability();
            row[5] = cars.getDate();
    
            model.addRow(row);
            
        }
    }
}
