/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Carui;

import Carinfo.Carproduct;
import java.awt.Image;
import Carinfo.Servicerecord;
import Carinfo.Servicerecordhistory;
import java.awt.Image;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.ImageIcon;
import java.io.File;

/**
 *
 * @author Sachin
 */
public class CreateDetails extends javax.swing.JPanel {

    /**
     * Creates new form CreateDetails
     */
    Carproduct carproduct;
    Servicerecordhistory history;
    String path_selected_file_photo;
    public CreateDetails(Carproduct carproduct, Servicerecordhistory history) {
        initComponents();
        this.carproduct = carproduct;
        this.history= history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jbrand = new javax.swing.JLabel();
        jmodel = new javax.swing.JLabel();
        jcolor = new javax.swing.JLabel();
        jyear = new javax.swing.JLabel();
        brand = new javax.swing.JTextField();
        model = new javax.swing.JTextField();
        color = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        jengineno = new javax.swing.JLabel();
        jseatsno = new javax.swing.JLabel();
        jlicenseplate = new javax.swing.JLabel();
        jtelephone = new javax.swing.JLabel();
        jownername = new javax.swing.JLabel();
        jemail = new javax.swing.JLabel();
        jaddress = new javax.swing.JLabel();
        jssn = new javax.swing.JLabel();
        jlicense = new javax.swing.JLabel();
        jwarrantyyear = new javax.swing.JLabel();
        engineno = new javax.swing.JTextField();
        seatsno = new javax.swing.JTextField();
        licenseplate = new javax.swing.JTextField();
        telephone = new javax.swing.JTextField();
        ownername = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        ssn = new javax.swing.JTextField();
        license = new javax.swing.JTextField();
        warrantyyear = new javax.swing.JTextField();
        upload = new javax.swing.JButton();
        jmileage = new javax.swing.JLabel();
        jage = new javax.swing.JLabel();
        jodometer = new javax.swing.JLabel();
        odometer = new javax.swing.JTextField();
        mileage = new javax.swing.JTextField();
        limit = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        icon = new javax.swing.JLabel();

        jLabel15.setText("service record:");

        setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create");

        jbrand.setText("brand:");

        jmodel.setText("model:");

        jcolor.setText("color:");

        jyear.setText("year :  ");

        brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandActionPerformed(evt);
            }
        });

        jengineno.setText("engine no:");

        jseatsno.setText("seatsno:");

        jlicenseplate.setText("licenseplate:");

        jtelephone.setText("telephone:");

        jownername.setText("ownername:");

        jemail.setText("email:");

        jaddress.setText("address:");

        jssn.setText("ssn:");

        jlicense.setText("license:");

        jwarrantyyear.setText("warranty year:");

        engineno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enginenoActionPerformed(evt);
            }
        });

        ssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnActionPerformed(evt);
            }
        });

        upload.setText("upload");
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });

        jmileage.setText("mileage:");

        jage.setText("limit:");

        jodometer.setText("odometer:");

        odometer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odometerActionPerformed(evt);
            }
        });

        mileage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mileageActionPerformed(evt);
            }
        });

        limit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limitActionPerformed(evt);
            }
        });

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jage)
                    .addComponent(jmileage)
                    .addComponent(jaddress)
                    .addComponent(jemail)
                    .addComponent(jssn)
                    .addComponent(jlicense)
                    .addComponent(jwarrantyyear)
                    .addComponent(jownername)
                    .addComponent(jtelephone)
                    .addComponent(jlicenseplate)
                    .addComponent(jseatsno)
                    .addComponent(jengineno)
                    .addComponent(jyear)
                    .addComponent(jcolor)
                    .addComponent(jmodel)
                    .addComponent(jbrand))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(warrantyyear, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(limit, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mileage, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(76, 76, 76)
                                .addComponent(Save))
                            .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jodometer)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(odometer, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upload)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(brand, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                    .addComponent(year)
                                    .addComponent(engineno)
                                    .addComponent(ownername)
                                    .addComponent(license)))
                            .addComponent(seatsno, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(licenseplate, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbrand, jcolor, jmodel, jyear});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbrand)
                    .addComponent(jodometer)
                    .addComponent(odometer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcolor)
                    .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jyear)
                    .addComponent(upload))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(engineno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jengineno))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jseatsno)
                            .addComponent(seatsno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlicenseplate)
                            .addComponent(licenseplate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtelephone)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jownername)
                            .addComponent(ownername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jemail)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jaddress)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jssn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlicense)
                    .addComponent(license, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jwarrantyyear)
                    .addComponent(warrantyyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jmileage)
                            .addComponent(mileage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jage)
                            .addComponent(limit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(Save)
                        .addGap(74, 74, 74))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enginenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enginenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enginenoActionPerformed

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
        JFileChooser filechooser = new  JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("3 Extensions supported", "jpg", "png", "gif");
        filechooser.setFileFilter(filter);
        int p = filechooser.showOpenDialog(null);
        if (p == JFileChooser.APPROVE_OPTION){
            File selected_file = filechooser.getSelectedFile();
            path_selected_file_photo = selected_file.getAbsolutePath();
            //JOptionPane.showMessageDialog(null, selected_Image_Path);
            //ImageIcon icn = new ImageIcon(selected_Image_Path);
            ImageIcon icn = new ImageIcon(new ImageIcon(path_selected_file_photo).getImage().getScaledInstance(238, 207,Image.SCALE_DEFAULT));
            //Image imFit = icn.getImage().getScaledInstance(icon.getWidth(), icon.getHeight(), Image.SCALE_SMOOTH);
            icon.setIcon(icn);
            
            
            
           
            
            
    }
    }//GEN-LAST:event_uploadActionPerformed

    private void brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandActionPerformed

    private void odometerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odometerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_odometerActionPerformed

    private void limitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limitActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        
        int flag = 0;
        String validationMessage = "";
         if(brand.getText().equals("")){
             flag = 1;
            //JOptionPane.showMessageDialog(null,"Name is required");
            validationMessage = "Name is required";
        } 
           
          if((email.getText() != "@" || email.getText() != ".")) {
              flag = 1;
              //JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
              validationMessage = validationMessage + "\n Please enter a valid email";
            }
          
             if(icon.getIcon() == null){
              flag = 1;
            //JOptionPane.showMessageDialog(null,"Profile Photo is required");
            validationMessage = validationMessage + "\n Profile Photo is required";
         }
             
        if (flag == 1){
            JOptionPane.showMessageDialog(this,validationMessage);
        }
        
        if(flag == 0)
        carproduct.setBrand(brand.getText());
        carproduct.setModel(model.getText());
        carproduct.setColor(color.getText());
        carproduct.setYear(Integer.parseInt(year.getText()));
        carproduct.setEngineno(Integer.parseInt(engineno.getText()));
        carproduct.setSeatsno(Integer.parseInt(seatsno.getText()));
        carproduct.setLicenseplate(licenseplate.getText());
        carproduct.setName(ownername.getText());
        carproduct.setTelephoneno(Integer.parseInt(telephone.getText()));
        carproduct.setEmailaddress(email.getText());
        carproduct.setDrivinglicense(license.getText());
        carproduct.setSSN(Integer.parseInt(ssn.getText()));
        carproduct.setAddress(address.getText());
        carproduct.setWarrantyyear(warrantyyear.getText());
        carproduct.setIcon(path_selected_file_photo);
        
        
        Servicerecord sr = history.addNewServicerecord();
        
        sr.setMileage(Integer.parseInt(mileage.getText()));
        sr.setLimit(Integer.parseInt(limit.getText()));
        sr.setOdometer(odometer.getText());
        
        
        
        
        JOptionPane.showMessageDialog(this,"Details saved");
        
    }//GEN-LAST:event_SaveActionPerformed

    private void mileageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mileageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mileageActionPerformed

    private void ssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Save;
    private javax.swing.JTextField address;
    private javax.swing.JTextField brand;
    private javax.swing.JTextField color;
    private javax.swing.JTextField email;
    private javax.swing.JTextField engineno;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jaddress;
    private javax.swing.JLabel jage;
    private javax.swing.JLabel jbrand;
    private javax.swing.JLabel jcolor;
    private javax.swing.JLabel jemail;
    private javax.swing.JLabel jengineno;
    private javax.swing.JLabel jlicense;
    private javax.swing.JLabel jlicenseplate;
    private javax.swing.JLabel jmileage;
    private javax.swing.JLabel jmodel;
    private javax.swing.JLabel jodometer;
    private javax.swing.JLabel jownername;
    private javax.swing.JLabel jseatsno;
    private javax.swing.JLabel jssn;
    private javax.swing.JLabel jtelephone;
    private javax.swing.JLabel jwarrantyyear;
    private javax.swing.JLabel jyear;
    private javax.swing.JTextField license;
    private javax.swing.JTextField licenseplate;
    private javax.swing.JTextField limit;
    private javax.swing.JTextField mileage;
    private javax.swing.JTextField model;
    private javax.swing.JTextField odometer;
    private javax.swing.JTextField ownername;
    private javax.swing.JTextField seatsno;
    private javax.swing.JTextField ssn;
    private javax.swing.JTextField telephone;
    private javax.swing.JButton upload;
    private javax.swing.JTextField warrantyyear;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables

    
}
